CREATE TABLE IF NOT EXISTS public.passenger_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ride_id TEXT NOT NULL,
  driver_id BIGINT NOT NULL,
  passenger_clerk_id TEXT NOT NULL,
  rating SMALLINT NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT passenger_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT passenger_ratings_ride_id_key UNIQUE (ride_id),
  CONSTRAINT passenger_ratings_comment_check
    CHECK (comment IS NULL OR char_length(comment) <= 500),
  CONSTRAINT passenger_ratings_rating_check
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE INDEX IF NOT EXISTS passenger_ratings_passenger_clerk_id_idx
  ON public.passenger_ratings USING btree (passenger_clerk_id);

CREATE INDEX IF NOT EXISTS passenger_ratings_driver_id_idx
  ON public.passenger_ratings USING btree (driver_id);
