CREATE TABLE IF NOT EXISTS public.passenger_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ride_id TEXT NOT NULL,
  driver_id BIGINT NOT NULL,
  passenger_clerk_id TEXT NOT NULL,
  rating SMALLINT NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT passenger_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT passenger_ratings_ride_id_key UNIQUE (ride_id),
  CONSTRAINT passenger_ratings_comment_check
    CHECK (comment IS NULL OR char_length(comment) <= 500),
  CONSTRAINT passenger_ratings_rating_check
    CHECK (rating >= 1 AND rating <= 5)
);

CREATE INDEX IF NOT EXISTS passenger_ratings_passenger_clerk_id_idx
  ON public.passenger_ratings USING btree (passenger_clerk_id);

CREATE INDEX IF NOT EXISTS passenger_ratings_driver_id_idx
  ON public.passenger_ratings USING btree (driver_id);

ALTER TABLE public.drivers
  ADD COLUMN IF NOT EXISTS rating_count INTEGER NOT NULL DEFAULT 0;

CREATE OR REPLACE FUNCTION public.record_passenger_driver_rating(
  p_ride_id TEXT,
  p_passenger_clerk_id TEXT,
  p_driver_id BIGINT,
  p_rating INTEGER,
  p_comment TEXT
)
RETURNS TABLE (average_rating NUMERIC, rating_count INTEGER)
LANGUAGE PLPGSQL
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_average_rating NUMERIC;
  v_rating_count INTEGER;
BEGIN
  PERFORM 1
  FROM public.drivers
  WHERE id = p_driver_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Driver not found';
  END IF;

  INSERT INTO public.passenger_ratings (
    ride_id,
    driver_id,
    passenger_clerk_id,
    rating,
    comment
  )
  VALUES (
    p_ride_id,
    p_driver_id,
    p_passenger_clerk_id,
    p_rating,
    p_comment
  );

  SELECT ROUND(AVG(rating)::NUMERIC, 1), COUNT(*)::INTEGER
  INTO v_average_rating, v_rating_count
  FROM public.passenger_ratings
  WHERE driver_id = p_driver_id;

  UPDATE public.drivers
  SET rating = v_average_rating,
      rating_count = v_rating_count
  WHERE id = p_driver_id;

  RETURN QUERY SELECT v_average_rating, v_rating_count;
END;
$$;

DROP TRIGGER IF EXISTS passenger_ratings_sync_user_rating
  ON public.passenger_ratings;

DROP FUNCTION IF EXISTS public.sync_passenger_rating();
DROP FUNCTION IF EXISTS public.refresh_passenger_rating(TEXT);

REVOKE ALL ON FUNCTION public.record_passenger_driver_rating(TEXT, TEXT, BIGINT, INTEGER, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_passenger_driver_rating(TEXT, TEXT, BIGINT, INTEGER, TEXT)
  TO service_role;

UPDATE public.drivers AS driver
SET rating = ratings.average_rating,
    rating_count = ratings.rating_count
FROM (
  SELECT driver_id,
         ROUND(AVG(rating)::NUMERIC, 1) AS average_rating,
         COUNT(*)::INTEGER AS rating_count
  FROM public.passenger_ratings
  GROUP BY driver_id
) AS ratings
WHERE driver.id = ratings.driver_id;
