CREATE TABLE IF NOT EXISTS public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  category TEXT NOT NULL CHECK (
    category IN (
      'booking',
      'hubs',
      'driver',
      'payment',
      'verification',
      'app-account',
      'safety'
    )
  ),
  message TEXT NOT NULL CHECK (
    char_length(message) BETWEEN 1 AND 1000
  ),
  ride_id BIGINT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (
    status IN ('open', 'pending', 'resolved')
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS support_tickets_user_created_idx
  ON public.support_tickets (user_id, created_at DESC);

ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
